/* Departamentos → municipios de Colombia (cliente). Espejo de Ubicaciones.gs.
   Extiende con el listado DIVIPOLA completo si lo necesitas. */
const UBICACIONES = {
  "Amazonas":["Leticia","Puerto Nariño"],
  "Antioquia":["Medellín","Bello","Itagüí","Envigado","Apartadó","Turbo","Rionegro","Sabaneta","Caldas","La Estrella","Copacabana","Girardota","Marinilla","Caucasia","Necoclí"],
  "Arauca":["Arauca","Arauquita","Saravena","Tame","Fortul","Puerto Rondón","Cravo Norte"],
  "Atlántico":["Barranquilla","Soledad","Malambo","Sabanalarga","Puerto Colombia","Galapa","Baranoa","Sabanagrande","Santo Tomás"],
  "Bogotá D.C.":["Bogotá D.C."],
  "Bolívar":["Cartagena","Magangué","Turbaco","El Carmen de Bolívar","Arjona","Mompós","María la Baja","San Juan Nepomuceno"],
  "Boyacá":["Tunja","Duitama","Sogamoso","Chiquinquirá","Paipa","Villa de Leyva","Puerto Boyacá","Nobsa","Moniquirá"],
  "Caldas":["Manizales","La Dorada","Chinchiná","Villamaría","Riosucio","Anserma","Supía","Aguadas"],
  "Caquetá":["Florencia","San Vicente del Caguán","Puerto Rico","El Doncello","Belén de los Andaquíes"],
  "Casanare":["Yopal","Aguazul","Villanueva","Tauramena","Paz de Ariporo","Monterrey","Maní"],
  "Cauca":["Popayán","Santander de Quilichao","Puerto Tejada","Patía","Guapi","Piendamó","Miranda"],
  "Cesar":["Valledupar","Aguachica","Agustín Codazzi","Bosconia","La Jagua de Ibirico","El Copey","Chiriguaná"],
  "Chocó":["Quibdó","Istmina","Tadó","Condoto","Riosucio","Bahía Solano","Nuquí"],
  "Córdoba":["Montería","Cereté","Sahagún","Lorica","Montelíbano","Planeta Rica","Tierralta","Ciénaga de Oro"],
  "Cundinamarca":["Soacha","Girardot","Zipaquirá","Facatativá","Chía","Fusagasugá","Mosquera","Madrid","Funza","Cajicá","Cota","Sibaté","Tocaima","Ricaurte"],
  "Guainía":["Inírida"],
  "Guaviare":["San José del Guaviare","Calamar","El Retorno","Miraflores"],
  "Huila":["Neiva","Pitalito","Garzón","La Plata","Campoalegre","Gigante","Aipe","Palermo"],
  "La Guajira":["Riohacha","Maicao","Uribia","Fonseca","San Juan del Cesar","Villanueva","Barrancas"],
  "Magdalena":["Santa Marta","Ciénaga","Fundación","El Banco","Plato","Zona Bananera","Aracataca"],
  "Meta":["Villavicencio","Acacías","Granada","Puerto López","San Martín","Cumaral","Restrepo"],
  "Nariño":["Pasto","Ipiales","Tumaco","Túquerres","La Unión","Sandoná","Samaniego"],
  "Norte de Santander":["Cúcuta","Ocaña","Villa del Rosario","Los Patios","Pamplona","Tibú","El Zulia"],
  "Putumayo":["Mocoa","Puerto Asís","Orito","Valle del Guamuez","Villagarzón","Sibundoy"],
  "Quindío":["Armenia","Calarcá","La Tebaida","Montenegro","Quimbaya","Circasia","Filandia"],
  "Risaralda":["Pereira","Dosquebradas","Santa Rosa de Cabal","La Virginia","Marsella","Belén de Umbría"],
  "San Andrés y Providencia":["San Andrés","Providencia"],
  "Santander":["Bucaramanga","Floridablanca","Girón","Piedecuesta","Barrancabermeja","San Gil","Socorro","Málaga"],
  "Sucre":["Sincelejo","Corozal","Sampués","San Marcos","Tolú","San Onofre","Majagual"],
  "Tolima":["Ibagué","Espinal","Flandes","Melgar","Honda","Líbano","Chaparral","Mariquita","Guamo","Purificación","Fresno","Cajamarca","Ortega","Saldaña","Venadillo","Lérida","Armero-Guayabal","Coello","Ambalema","Suárez","San Luis","Rovira","Icononzo","Natagaima","Coyaima"],
  "Valle del Cauca":["Cali","Buenaventura","Palmira","Tuluá","Cartago","Buga","Jamundí","Yumbo","Candelaria","Florida","Pradera","Zarzal"],
  "Vaupés":["Mitú","Carurú","Taraira"],
  "Vichada":["Puerto Carreño","La Primavera","Santa Rosalía","Cumaribo"]
};
